### ISSUE TITLE
Change Default branch?

### ISSUE THREAD

**Issue by laceysanderson** [tripal/brapi#19]
As we're now developing on 7.x-3.x, we should change the default branch for this repository. 

The reason I bring this up is that it impacts which README is shown to users. Currently, even though PR #18 is merged, no one sees the new README. This means, no one is told there is more documentation available...

**Comment by guignonv** [comment]
I think, even if there is (should be) the same content on both branches at the moment, default should go to 3.x to show it's Tripal 3 compatible while this branch is ALSO 2.x compatible. Branch 1.x should be abandoned and removed if we implement Tripal 3 service classes and find no issue preventing backward compatibility with Tripal 2.
Done.
