### ISSUE TITLE
Trait terms limitation

### ISSUE THREAD

**Issue by guignonv** [tripal/brapi#22]
Only trait-related CV terms should be returned by the traits/ call. This issue should be solved after issue #21 has been fixed. Then, fields should be added on the setting page to select CVs containing traits and parent CV terms of trait CV terms, the same way it has been done for germplasm attributes.

**Comment by ekcannon** [comment]
Ah. And the same problem exists for the /variables call, so I should be able to fix both at the same time.

**Comment by guignonv** [comment]
Fixed by commit 824336af9065bd84f7422d1f4d417b8385b151d2.
