### ISSUE TITLE
Fix BRAVA error on Germplasm biologicalStatusOfAccessionCode  retrieval

### ISSUE THREAD

**Issue by RichardBruskiewich** [tripal/brapi#24]
BrAPI BRAVA failed  test  for /germplasm-search
**Test Json matches schema: /schemas/v1.2/germplasm-search.json**

Error: validation - type
In element: /result/data/1/biologicalStatusOfAccessionCode
Expected: integer, null
Found: string
Message: instance type (string) does not match any allowed primitive type (allowed: ["integer","null"])

**Comment by guignonv** [comment]
Fixed by commit 8dde5497d455d79d33e8c438f6bc801531cdf798
