### ISSUE TITLE
Fix BRAVA error on Germplasm marker profiles retrieval

### ISSUE THREAD

**Issue by RichardBruskiewich** [tripal/brapi#26]
BrAPI BRAVA failed test for /germplasm-search

/germplasm/{germplasmDbId}/markerprofiles (wrong status code)

**Test: Status code should be 200**

**Comment by guignonv** [comment]
The call tested by BRAVA was proxied to Gigwa and there is no issue on the Drupal module in fact. Thanks for reporting though.
