### ISSUE TITLE
 Fix  BRAVA Error on  /locations listing  of location data

### ISSUE THREAD

**Issue by RichardBruskiewich** [tripal/brapi#27]
BRAVA Test  Failure:

**Test: Json matches schema: /schemas/v1.2/locations.json**

Response structure doesn't match Schema.

Error: validation - type
In element: /result/data/*/name
Expected: string
Found: null
Message: instance type (null) does not match any allowed primitive type (allowed: ["string"])

(note: '*' denotes any number of  location id's

**Comment by guignonv** [comment]
Fixed by commit 91622f26264e8506c889b4fed3aa9b8b94ec7120
