### ISSUE TITLE
Fix BRAVA Error on /locations/{locationId} reading of location data record

### ISSUE THREAD

**Issue by RichardBruskiewich** [tripal/brapi#29]
Failed  BRAVA test:

**Test: Json matches schema: /schemas/v1.2/locationsDbId.json**

Error: validation - type
In element: /result
Expected: object
Found: array
Message: instance type (array) does not match any allowed primitive type (allowed: ["object"])

**Comment by guignonv** [comment]
Fixed by commit 9ccc591a3d204999f3729b8a9a4a86f18cae153b.
