### ISSUE TITLE
Failed attempt to install latest (commit 962ffe4) Tripal Brapi module inside docker-tripal v3.x

### ISSUE THREAD

**Issue by RichardBruskiewich** [tripal/brapi#3]
In an exploratory way, I attempt to add in the BrAPI module into the tripal service of the dockerized-gmod-deployment (master branch, latest commit 135079e) docker-compose build. Here's the relevant failure point in the log: 

tripal_1               | WD system: brapi_site module installed.                                   [info]
tripal_1               | WD system: brapi_site module enabled.                                     [info]
tripal_1               | WD php: Error: Call to undefined function tripal_cv_load_obo_v1_2()      [error]
tripal_1               | in brapi_add_cvs() (line 206 of
tripal_1               | /var/www/html/sites/all/modules/brapi/brapi.install).
tripal_1               | Cannot modify header information - headers already sent by (output     [warning]
tripal_1               | started at /root/.composer/vendor/drush/drush/includes/output.inc:40)
tripal_1               | bootstrap.inc:1486
tripal_1               | Error: Call to undefined function tripal_cv_load_obo_v1_2() in brapi_add_cvs() (line 206 of /var/www/html/sites/all/modules/brapi/brapi.install).
tripal_1               | Drush command terminated abnormally due to an unrecoverable error.       [error]
tripal_1               | A non well formed numeric value encountered drush.inc:1643              [notice]

**Comment by guignonv** [comment]
It seems that Tripal 3 has renamed the function "tripal_cv_load_obo_v1_2" into "tripal_cv_load_obo". I will investigate to see if they behave the same way.

**Comment by guignonv** [comment]
I did a fix for Tripal 3 on the 2 last commits. Could you try with the last dev version?

**Comment by guignonv** [comment]
#7 
Should be fixed by the last commit (3548773ac5bb2d0909145dc1c51392d4c55a2767)

**Comment by guignonv** [comment]
No news. Closing issue as other people can now install BrAPI on Tripal v3.

**Comment by RichardBruskiewich** [comment]
Thanks Valentin, I'll try installing the module again.
