### ISSUE TITLE
Fix BRAVA Error on metadata model of various endpoints

### ISSUE THREAD

**Issue by RichardBruskiewich** [tripal/brapi#30]
Failed BRAVA test: Response structure doesn't match schema:

**Test: Json matches schema: /schemas/v1.2/metadata.json**

Error: validation - additionalProperties
In element: /metadata
Invalid items: aggregated_from
Message: object instance has properties which are not allowed by the schema: ["aggregated_from"]

**Comment by guignonv** [comment]
Fixed by commit f7d4e97a17ff041cd74f0ae6394f13ad9192507e.
