### ISSUE TITLE
Fix install on Tripal 3 with legacy support enabled

### ISSUE THREAD

**Issue by guignonv** [tripal/brapi#6]
The tripal_cv_load_obo_v1_2 function is not available.

**Comment by laceysanderson** [comment]
The problem is due to the fact that the legacy obo loader was removed when the new one was created.

**Comment by laceysanderson** [comment]
Fixed this by using the new obo loader when it is available and only reverting to the old obo loader when it's the only one.

**Comment by laceysanderson** [comment]
Closing since PR fixing it has been merged
